=== orpiske/nus/src/xml/examples/nxmlreader-2.dtd
<!ELEMENT programming_languages (language*)>

<!ELEMENT language (type,compiler*,interpreter*)>
<!ATTLIST language name CDATA #REQUIRED>

<!ELEMENT type (#PCDATA)>
<!ELEMENT compiler (#PCDATA)>
<!ELEMENT interpreter (#PCDATA)>

=== orpiske/nus/src/xml/examples/nxmlreader-2.xml
<?xml version="1.0"?>
<!DOCTYPE programming_languages SYSTEM "nxmlreader-2.dtd">
<programming_languages>
	<language name="c++">
		<type>compiled</type>
		<compiler>g++</compiler>
		<compiler>icc</compiler>
	</language>
	<language name="python">
		<type>interpreted</type>
		<interpreter>python</interpreter>
	</language>
</programming_languages>

=== orpiske/nus/src/xml/examples/nxmlreader-2_typo.xml
<?xml version="1.0"?>
<!DOCTYPE programming_languages SYSTEM "nxmlreader-2.dtd">
<programming_languages>
	<language name="c++">
		<!-- Note the small, subtle typo above -->
		<tipe>compiled</tipe>
		<compiler>g++</compiler>
		<compiler>icc</compiler>
	</language>
	<language name="python">
		<type>interpreted</type>
		<interpreter>python</interpreter>
	</language>
</programming_languages>
